"""make player_id nullable

Revision ID: 7482f561db17
Revises: 
Create Date: 2026-04-29 18:19:18.494656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7482f561db17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'FINISHED', name='gamestatus'), nullable=True),
    sa.Column('chaos_level', sa.Integer(), nullable=True),
    sa.Column('disaster_description', sa.Text(), nullable=True),
    sa.Column('bunker_capacity', sa.Integer(), nullable=True),
    sa.Column('bunker_years', sa.Integer(), nullable=True),
    sa.Column('bunker_features_json', sa.JSON(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('active_player_idx', sa.Integer(), nullable=True),
    sa.Column('finale_text', sa.Text(), nullable=True),
    sa.Column('last_action_log', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_dead', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_tg_user_id'), 'players', ['tg_user_id'], unique=True)
    op.create_table('cards',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('PROFESSION', 'appearance', 'HEALTH', 'INVENTORY', 'BIOLOGY', 'ABILITY', 'PHOBIA', 'HOBBY', 'FACT', name='cardtype'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('power_level', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('chaos_level', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.Enum('HEAL', 'STEAL', 'SPOIL', 'GIFT', 'SPAWN', 'CHANGE_GENDER', 'REVEAL', 'SWAP_TRAIT', 'REVIVE', name='actionenum'), nullable=True),
    sa.Column('base_success_chance', sa.Integer(), nullable=True),
    sa.Column('is_revealed', sa.Boolean(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('cards')
    op.drop_index(op.f('ix_players_tg_user_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
